version: "3.5"

services:
    app:
        build: .
        entrypoint: ""
        command: sleep infinity
        user: node:node
        volumes:
            - .:/app:rw
            - ohw-vscode-extensions:/home/app/.vscode-server/extensions
            - ohw-vscode-insiders-extensions:/home/app/.vscode-server-insiders/extensions
        environment:
            HISTFILE: /app/.bash_history
        restart: unless-stopped

volumes:
    ohw-vscode-extensions:
    ohw-vscode-insiders-extensions:
