services:
    app:
        build: .
        entrypoint: ""
        command: sleep infinity
        user: node:node
        volumes:
            - .:/app:rw
        environment:
            HISTFILE: /app/.bash_history
        restart: unless-stopped

volumes:
    ohw-vscode-extensions:
    ohw-vscode-insiders-extensions:
